import type { Recipe, Ingredient } from "./planner";
const ingredients = (items: [string, number, number][]): Ingredient[] =>
  items.map(([name, grams, costCents]) => ({ name, grams, costCents }));
// Hand-authored illustrative recipes: prices and nutrition are demo estimates,
// not USDA calculations, product-label verification, or live store quotes.
export const sampleRecipes: Recipe[] = [
  {
    id: "oats",
    name: "Apple cinnamon oats",
    description: "A warm bowl of oats with soft apple and a little crunch.",
    cuisine: "American",
    kind: "vegan",
    allergens: ["Tree nuts"],
    occasion: "breakfast",
    minutes: 12,
    art: "bowl",
    ingredients: ingredients([
      ["Certified gluten-free rolled oats, dry", 50, 25],
      ["Apple, diced", 100, 45],
      ["Walnuts", 10, 25],
      ["Cinnamon", 1, 5],
    ]),
    steps: [
      "Simmer oats in 180 ml water for 5 minutes, stirring.",
      "Add the diced apple and cinnamon; cook until the apple softens.",
      "Top with chopped walnuts and serve warm.",
    ],
    nutrition: { calories: 310, protein: 8, carbs: 47, fat: 11, fiber: 8 },
  },
  {
    id: "toast",
    name: "Avocado & egg toast",
    description: "Crisp whole-wheat toast, creamy avocado, and a soft egg.",
    cuisine: "American",
    kind: "vegetarian",
    allergens: ["Wheat", "Eggs"],
    occasion: "breakfast",
    minutes: 10,
    art: "toast",
    ingredients: ingredients([
      ["Whole-wheat bread", 60, 40],
      ["Avocado, edible flesh", 60, 65],
      ["Egg, without shell", 50, 35],
      ["Black pepper", 1, 3],
    ]),
    steps: [
      "Toast the bread and mash the avocado with pepper.",
      "Cook the egg to your preference.",
      "Spread avocado on toast and top with the egg.",
    ],
    nutrition: { calories: 340, protein: 14, carbs: 32, fat: 18, fiber: 7 },
  },
  {
    id: "yogurt",
    name: "Berry yogurt bowl",
    description: "Thick yogurt with berries and toasted oat flakes.",
    cuisine: "Mediterranean",
    kind: "vegetarian",
    allergens: ["Milk"],
    occasion: "breakfast",
    minutes: 5,
    art: "bowl",
    ingredients: ingredients([
      ["Plain Greek yogurt", 170, 80],
      ["Blueberries", 60, 55],
      ["Certified gluten-free oats, dry", 25, 15],
    ]),
    steps: [
      "Spoon yogurt into a bowl.",
      "Add washed berries and sprinkle with oats.",
    ],
    nutrition: { calories: 265, protein: 20, carbs: 31, fat: 7, fiber: 4 },
  },
  {
    id: "chickpea",
    name: "Lemony chickpea bowl",
    description: "Golden chickpeas, brown rice, and a bright lemon dressing.",
    cuisine: "Mediterranean",
    kind: "vegan",
    allergens: [],
    occasion: "main",
    minutes: 25,
    art: "bowl",
    ingredients: ingredients([
      ["Chickpeas, canned, drained", 140, 65],
      ["Brown rice, dry", 60, 25],
      ["Cucumber", 80, 30],
      ["Tomato", 80, 35],
      ["Lemon juice", 15, 15],
      ["Olive oil", 8, 12],
    ]),
    steps: [
      "Cook the dry rice according to the package directions.",
      "Rinse and drain chickpeas; dice cucumber and tomato.",
      "Combine rice and vegetables, then dress with lemon juice and olive oil.",
    ],
    nutrition: { calories: 510, protein: 17, carbs: 77, fat: 15, fiber: 13 },
  },
  {
    id: "tacos",
    name: "Sweet potato & bean tacos",
    description: "Roasted sweet potato and black beans in soft corn tortillas.",
    cuisine: "Mexican",
    kind: "vegan",
    allergens: [],
    occasion: "main",
    minutes: 30,
    art: "wrap",
    ingredients: ingredients([
      ["Sweet potato, raw", 150, 50],
      ["Black beans, canned, drained", 100, 45],
      ["Corn tortillas", 60, 45],
      ["Tomato salsa", 40, 25],
      ["Olive oil", 5, 8],
    ]),
    steps: [
      "Dice sweet potato, coat in oil, and roast at 425°F for 20–25 minutes.",
      "Warm drained beans and tortillas separately.",
      "Fill tortillas with beans and sweet potato; spoon over salsa.",
    ],
    nutrition: { calories: 460, protein: 13, carbs: 81, fat: 10, fiber: 15 },
  },
  {
    id: "dal",
    name: "Red lentil dal & rice",
    description:
      "A gently spiced lentil pot that makes the next day easier, too.",
    cuisine: "Indian",
    kind: "vegan",
    allergens: [],
    occasion: "main",
    minutes: 30,
    art: "bowl",
    ingredients: ingredients([
      ["Red lentils, dry", 65, 35],
      ["White rice, dry", 55, 22],
      ["Tomato, canned", 100, 35],
      ["Onion", 50, 15],
      ["Curry powder", 3, 12],
      ["Olive oil", 5, 8],
    ]),
    steps: [
      "Cook rice following its package instructions.",
      "Soften chopped onion in oil, then stir in curry powder.",
      "Add rinsed lentils, tomatoes, and 250 ml water. Simmer 20 minutes until tender, adding water if needed.",
      "Serve dal over rice.",
    ],
    nutrition: { calories: 480, protein: 21, carbs: 83, fat: 7, fiber: 11 },
  },
  {
    id: "tofu",
    name: "Ginger tofu rice bowl",
    description: "Crisp tofu and broccoli with a quick ginger-tamari glaze.",
    cuisine: "East Asian",
    kind: "vegan",
    allergens: ["Soy", "Sesame"],
    occasion: "main",
    minutes: 25,
    art: "bowl",
    ingredients: ingredients([
      ["Firm tofu", 140, 90],
      ["Brown rice, dry", 60, 25],
      ["Broccoli, raw", 100, 45],
      ["Gluten-free tamari", 15, 15],
      ["Ginger", 5, 8],
      ["Sesame oil", 5, 12],
    ]),
    steps: [
      "Cook rice and steam broccoli until tender.",
      "Pat tofu dry, cube it, and pan-fry in sesame oil.",
      "Add grated ginger and tamari. Toss and serve with rice and broccoli.",
    ],
    nutrition: { calories: 490, protein: 25, carbs: 57, fat: 19, fiber: 7 },
  },
  {
    id: "chicken",
    name: "Herby chicken & potatoes",
    description: "One tray of chicken, golden potatoes, and green beans.",
    cuisine: "Mediterranean",
    kind: "meat",
    allergens: [],
    occasion: "main",
    minutes: 35,
    art: "bowl",
    ingredients: ingredients([
      ["Chicken breast, raw", 150, 155],
      ["Potatoes, raw", 180, 50],
      ["Green beans, raw", 100, 45],
      ["Olive oil", 8, 12],
      ["Dried mixed herbs", 2, 10],
    ]),
    steps: [
      "Heat oven to 425°F. Cut potatoes into small pieces and toss with half the oil and herbs.",
      "Roast potatoes for 10 minutes. Add chicken and green beans with remaining oil.",
      "Roast until chicken reaches 165°F internally and potatoes are tender, approximately 20 more minutes.",
    ],
    nutrition: { calories: 450, protein: 39, carbs: 42, fat: 13, fiber: 6 },
  },
  {
    id: "pasta",
    name: "Tomato & spinach pasta",
    description: "A familiar weeknight pasta with wilted greens and parmesan.",
    cuisine: "Mediterranean",
    kind: "vegetarian",
    allergens: ["Wheat", "Milk"],
    occasion: "main",
    minutes: 20,
    art: "bowl",
    ingredients: ingredients([
      ["Whole-wheat pasta, dry", 80, 40],
      ["Crushed tomatoes", 150, 50],
      ["Spinach", 50, 35],
      ["Vegetarian parmesan-style cheese", 15, 35],
      ["Olive oil", 5, 8],
    ]),
    steps: [
      "Boil pasta according to package instructions; reserve a little cooking water.",
      "Simmer tomatoes in olive oil and stir in spinach until wilted.",
      "Toss with pasta, loosen with cooking water, and finish with cheese.",
    ],
    nutrition: { calories: 425, protein: 18, carbs: 66, fat: 12, fiber: 10 },
  },
  {
    id: "salmon",
    name: "Salmon & green rice",
    description: "Flaky salmon over rice with tender broccoli and lemon.",
    cuisine: "American",
    kind: "fish",
    allergens: ["Fish"],
    occasion: "main",
    minutes: 30,
    art: "bowl",
    ingredients: ingredients([
      ["Salmon, raw", 130, 265],
      ["Brown rice, dry", 55, 23],
      ["Broccoli, raw", 100, 45],
      ["Lemon juice", 15, 15],
      ["Olive oil", 5, 8],
    ]),
    steps: [
      "Cook rice according to the package directions.",
      "Brush salmon with oil and bake at 400°F until its internal temperature reaches 145°F.",
      "Steam broccoli and serve with rice, salmon, and lemon juice.",
    ],
    nutrition: { calories: 535, protein: 34, carbs: 49, fat: 23, fiber: 6 },
  },
  {
    id: "scramble",
    name: "Spiced tofu scramble",
    description: "A colorful skillet of tofu, peppers, and tender spinach.",
    cuisine: "Indian",
    kind: "vegan",
    allergens: ["Soy"],
    occasion: "breakfast",
    minutes: 15,
    art: "bowl",
    ingredients: ingredients([
      ["Firm tofu", 150, 95],
      ["Bell pepper", 80, 40],
      ["Spinach", 40, 28],
      ["Turmeric", 1, 5],
      ["Olive oil", 5, 8],
    ]),
    steps: [
      "Soften diced pepper in oil in a skillet.",
      "Crumble in tofu and add turmeric; cook for 5 minutes.",
      "Fold in spinach and cook until wilted.",
    ],
    nutrition: { calories: 280, protein: 22, carbs: 12, fat: 18, fiber: 5 },
  },
  {
    id: "ricebreakfast",
    name: "Banana breakfast rice",
    description: "Warm rice with banana, cinnamon, and creamy coconut milk.",
    cuisine: "East Asian",
    kind: "vegan",
    allergens: [],
    occasion: "breakfast",
    minutes: 20,
    art: "bowl",
    ingredients: ingredients([
      ["White rice, dry", 50, 20],
      ["Banana, peeled", 100, 25],
      ["Coconut milk", 60, 35],
      ["Cinnamon", 1, 5],
    ]),
    steps: [
      "Cook rice with 150 ml water until tender.",
      "Stir in coconut milk and sliced banana. Warm gently and finish with cinnamon.",
    ],
    nutrition: { calories: 350, protein: 5, carbs: 65, fat: 9, fiber: 3 },
  },
  {
    id: "hummus",
    name: "Hummus & crunchy veg",
    description: "A small plate of creamy hummus and crisp vegetable sticks.",
    cuisine: "Mediterranean",
    kind: "vegan",
    allergens: ["Sesame"],
    occasion: "snack",
    minutes: 5,
    art: "bowl",
    ingredients: ingredients([
      ["Hummus", 70, 65],
      ["Carrots, raw", 100, 25],
      ["Cucumber", 80, 30],
    ]),
    steps: [
      "Wash the vegetables and cut into sticks.",
      "Serve alongside a generous spoonful of hummus.",
    ],
    nutrition: { calories: 215, protein: 7, carbs: 24, fat: 11, fiber: 7 },
  },
  {
    id: "applepb",
    name: "Apple & peanut butter",
    description: "Sweet apple wedges and a little peanut butter for dipping.",
    cuisine: "American",
    kind: "vegan",
    allergens: ["Peanuts"],
    occasion: "snack",
    minutes: 5,
    art: "toast",
    ingredients: ingredients([
      ["Apple", 150, 55],
      ["Peanut butter", 25, 20],
    ]),
    steps: [
      "Core and slice the apple.",
      "Serve with peanut butter for dipping.",
    ],
    nutrition: { calories: 225, protein: 7, carbs: 27, fat: 13, fiber: 5 },
  },
  {
    id: "quesadilla",
    name: "Bean & cheese quesadilla",
    description:
      "A crisp tortilla filled with beans, melted cheese, and salsa.",
    cuisine: "Mexican",
    kind: "vegetarian",
    allergens: ["Wheat", "Milk"],
    occasion: "main",
    minutes: 15,
    art: "wrap",
    ingredients: ingredients([
      ["Wheat tortilla", 60, 40],
      ["Black beans, canned, drained", 100, 45],
      ["Cheddar cheese", 30, 40],
      ["Salsa", 40, 25],
    ]),
    steps: [
      "Place beans and grated cheese on half a tortilla, then fold.",
      "Cook in a dry skillet for 2–3 minutes per side until crisp and melted.",
      "Cut into wedges and serve with salsa.",
    ],
    nutrition: { calories: 450, protein: 22, carbs: 58, fat: 16, fiber: 10 },
  },
];
