import { readFile, writeFile, mkdir } from "node:fs/promises";
import { resolve, relative, isAbsolute } from "node:path";
import { fileURLToPath } from "node:url";
import {
  object,
  toFoodRow,
  sqlJson,
  splitSqlBatches,
  type FoodRow,
} from "./food-import";

async function main() {
  const root = fileURLToPath(new URL("../", import.meta.url));
  const base = resolve(root, "data/usda");
  const manifest: unknown = JSON.parse(
    await readFile(resolve(base, "foundation-manifest.json"), "utf8"),
  );
  if (!Array.isArray(manifest) || manifest.length !== 300)
    throw new Error("Expected 300 manifest entries");
  const ids = new Set<number>();
  const paths = new Set<string>();
  const rows: FoodRow[] = [];
  for (const value of manifest) {
    const entry = object(value, "manifest entry");
    if (
      typeof entry.fdcId !== "number" ||
      typeof entry.file !== "string" ||
      typeof entry.name !== "string"
    )
      throw new Error("Invalid manifest entry");
    const path = resolve(base, entry.file);
    const inside = relative(resolve(base, "foundation"), path);
    if (
      inside.startsWith("..") ||
      isAbsolute(inside) ||
      !path.endsWith(".json")
    )
      throw new Error("Manifest path must be inside the Foundation folder");
    if (ids.has(entry.fdcId) || paths.has(path))
      throw new Error("Duplicate manifest ID or path");
    ids.add(entry.fdcId);
    paths.add(path);
    rows.push(
      toFoodRow(
        JSON.parse(await readFile(path, "utf8")),
        entry.fdcId,
        entry.name,
      ),
    );
  }
  rows.sort((a, b) => a.fdc_id - b.fdc_id);
  const negativeCarbohydrates = rows.flatMap((row) => {
    const food = object(row.source_record.food, "food");
    const ns = food.foodNutrients as unknown[];
    return ns
      .map((n) => object(n, "nutrient"))
      .filter(
        (n) =>
          String(n.number) === "205" &&
          typeof n.amount === "number" &&
          n.amount < 0,
      )
      .map((n) => ({
        fdcId: row.fdc_id,
        description: row.description,
        nutrientNumber: "205",
        sourceAmount: n.amount,
        unitName: n.unitName,
        action:
          "Imported carbohydrate column as NULL; original source preserved",
      }));
  });

  const columns = Object.keys(rows[0]);
  const updates = columns
    .filter((c) => c !== "fdc_id")
    .map((c) => `  ${c} = EXCLUDED.${c}`)
    .join(",\n");
  const estimated = rows.filter((r) => r.calories_is_estimate === true).length;
  const missing = rows.filter((r) => r.calories_kcal_per_100g === null).length;
  const makeSeed = (batch: FoodRow[]) =>
    `-- Generated by npm run export:foods. Do not edit manually.\n-- ${batch.length} foods. For SQL Editor, use the numbered files in foods-seed-batches/.\nBEGIN;\nSET LOCAL standard_conforming_strings = on;\nCREATE TEMP TABLE food_import (LIKE public.foods INCLUDING ALL) ON COMMIT DROP;\nINSERT INTO food_import (${columns.join(", ")})\nSELECT ${columns.join(", ")} FROM jsonb_populate_recordset(NULL::public.foods,\n${sqlJson(batch)}\n);\nINSERT INTO public.foods (${columns.join(", ")})\nSELECT ${columns.join(", ")} FROM food_import\nON CONFLICT (fdc_id) DO UPDATE SET\n${updates};\nCOMMIT;\n`;
  const seed = makeSeed(rows);
  const batches = splitSqlBatches(rows, makeSeed);
  const verify = `-- Read-only verification of the current manifest, excluding unrelated rows.\nWITH expected AS (SELECT jsonb_array_elements_text(${sqlJson(rows.map((r) => r.fdc_id))})::bigint AS fdc_id)\nSELECT count(*) AS expected_foods, count(f.fdc_id) AS imported_foods,\n count(*) FILTER (WHERE f.fdc_id IS NULL) AS missing_rows,\n count(*) FILTER (WHERE f.calories_is_estimate IS TRUE) AS estimated_calories,\n count(*) FILTER (WHERE f.fdc_id IS NOT NULL AND f.calories_kcal_per_100g IS NULL) AS unknown_calories\nFROM expected e LEFT JOIN public.foods f USING (fdc_id);\n-- Expected: 300, 300, 0, ${estimated}, ${missing}.\n\nSELECT fdc_id, calories_kcal_per_100g, calories_is_estimate\nFROM public.foods WHERE fdc_id = 746775; -- Salt: 0, true.\n\nSELECT relrowsecurity FROM pg_class WHERE oid = 'public.foods'::regclass; -- true\nSELECT policyname, roles, cmd FROM pg_policies WHERE schemaname = 'public' AND tablename = 'foods';\n-- Only the SELECT policy for anon/authenticated.\n`;
  await mkdir(resolve(root, "supabase"), { recursive: true });
  await writeFile(resolve(root, "supabase/foods-seed.sql"), seed);
  const batchDir = resolve(root, "supabase/foods-seed-batches");
  await mkdir(batchDir, { recursive: true });
  const index = [];
  for (const [i, batch] of batches.entries()) {
    const file = `foods-${String(i + 1).padStart(3, "0")}.sql`;
    await writeFile(resolve(batchDir, file), batch.sql);
    index.push({
      file,
      rows: batch.rowCount,
      bytes: Buffer.byteLength(batch.sql, "utf8"),
    });
  }
  await writeFile(
    resolve(batchDir, "index.json"),
    JSON.stringify(index, null, 2) + "\n",
  );
  await writeFile(
    resolve(batchDir, "README.md"),
    "# SQL Editor import batches\n\nRun each linked file below in a separate SQL Editor query, in order.\nThe foods table must already exist. Each file is transactional and safe to rerun.\nUse this index, not a folder glob: files from older exports may remain.\n\n" +
      index
        .map(
          (x) => `- [${x.file}](${x.file}): ${x.rows} foods, ${x.bytes} bytes`,
        )
        .join("\n") +
      "\n\nAfter all batches, run [verification](../verify-foods.sql). Expect 300 foods.\n",
  );

  await writeFile(resolve(root, "supabase/verify-foods.sql"), verify);
  await writeFile(
    resolve(root, "supabase/foods-import-report.json"),
    JSON.stringify(
      {
        foodCount: rows.length,
        calorieEstimates: estimated,
        unknownCalories: missing,
        negativeCarbohydrates,
      },
      null,
      2,
    ) + "\n",
  );
  console.log(
    `Exported ${rows.length} foods: ${estimated} estimated calories, ${missing} unknown calories. ${batches.length} SQL Editor batches generated. No database was contacted.`,
  );
}
main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : "Export failed");
  process.exitCode = 1;
});
